version: '3'

services: 
  frontend-service:
    build: .
    ports:
     - '3000:3000'
    volumes: 
      - /app/node_modules
      - .:/app
  frontend-service-dev:
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
     - '3001:3000'
    volumes: 
      - /app/node_modules
      - .:/app
  tests:
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    command: ["yarn", "test"]
    volumes: 
      - /app/node_modules
      - .:/app